export const ROUTE_ATRIUM = 'Atrium'
export const ROUTE_SESSIONS = 'Sessions'
export const ROUTE_SCHEDULE = 'Schedule'
export const ROUTE_COFFEE_CHAT = 'CoffeeChat'
export const ROUTE_HELP = 'Help'
export const ROUTE_PROFILE = 'Profile'

export const ROUTE_TERMS = 'Terms'
export const ROUTE_PRIVACY = 'Privacy'
export const ROUTE_GUIDELINES = 'Guidelines'
export const ROUTE_ERROR = 'Error'

export const ROUTE_EVENT = 'Event'
export const ROUTE_LOGIN = 'Login'
export const ROUTE_REGISTER = 'Register'
export const ROUTE_TOKEN_CAPTURE = 'TokenCapture'
export const ROUTE_NOT_FOUND = 'NotFound'
export const ROUTE_TRANSLATOR = 'Translator'

export const ROUTE_INTERPRET_HOME = 'InterpretHome'
export const ROUTE_INTERPRET = 'Interpret'

export const STORAGE_ANALYTICS = 'analyticsConsent'
export const STORAGE_LOCALE = 'chosenLocale'
export const STORAGE_TOKEN = 'token'
