#
# A GitHub workflow to build a container for each semantically versioned tag (i.e. vX.Y.Z).
#
# help:
# - tagging info: https://github.com/docker/build-push-action/blob/v2/docs/advanced/tags-labels.md
# - original gist: https://gist.github.com/robb-j/049217ca8cecf4e214b8b82123f7371b
#

name: 'Build Versioned Container'

on:
  push:
    tags: [v*.*.*]

env:
  REGISTRY: ghcr.io/digitalinteraction/climatered-client

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate container metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}
          tags: |
            type=semver,pattern={{version}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
