#
# refs:
# - https://github.com/marketplace/actions/build-and-push-docker-images
# - https://help.github.com/en/actions/language-and-framework-guides/publishing-docker-images
# - https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token
#

name: Publish docker image
on:
  push:
    tags: [v*]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: openlab/ifrc-vconf-gui
          tag_with_ref: true

      - name: slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          JSON=`cat <<EOF
          {
            "text": "build $GITHUB_REPOSITORY for $GITHUB_REF"
          }`
          curl -X POST --data-urlencode "payload=$JSON" $SLACK_WEBHOOK
