#
# refs:
# - https://github.com/marketplace/actions/build-and-push-docker-images
# - https://help.github.com/en/actions/language-and-framework-guides/publishing-docker-images
# - https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token
#

name: Publish docker image

on: [pull_request]

env:
  REGISTRY: ghcr.io/digitalinteraction/climatered-client

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate container metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}
          tags: |
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
